/**
 * JJazzLab drum patterns — derived from drums44DB.mid (JJazzLab JJSwing, LGPL v2.1).
 * Use for DrumEngine / pattern registry (Ride, Brushes, Shuffle, Intro, Ending, etc.).
 * Generated by: node scripts/import-jjazzlab-drums.mjs
 * @see https://www.jjazzlab.org
 */

import type { JJazzLabDrumPattern } from "./jjazzlab-drum-patterns.types";
import patternsData from "./jjazzlab-drum-patterns.json";

const patterns: JJazzLabDrumPattern[] = patternsData as JJazzLabDrumPattern[];

export { patterns as JJAZZLAB_DRUM_PATTERNS };
export type { JJazzLabDrumPattern, JJazzLabDrumEvent, JJazzLabDrumInstrument } from "./jjazzlab-drum-patterns.types";

/** Get all patterns for a given DrumsStyle id (e.g. RIDE_1, BRUSHES_1). */
export function getDrumPatternsByStyle(styleId: string): JJazzLabDrumPattern[] {
  return patterns.filter((p) => p.styleId === styleId);
}
